-- Seed data: taxonomy, merchant rules, and budget targets from Phase 0.
-- Run AFTER schema.sql. Safe to re-run: every insert uses ON CONFLICT or a
-- unique guard, so running this file twice never creates duplicates.

-- ---- Categories ----
insert into categories (name, tier, type, counts_toward_runrate, sort_order) values ('Rent', 1, 'fixed', true, 1) on conflict (name) do nothing;
insert into categories (name, tier, type, counts_toward_runrate, sort_order) values ('Phone', 1, 'fixed', true, 2) on conflict (name) do nothing;
insert into categories (name, tier, type, counts_toward_runrate, sort_order) values ('Internet', 1, 'fixed', true, 3) on conflict (name) do nothing;
insert into categories (name, tier, type, counts_toward_runrate, sort_order) values ('Groceries', 1, 'variable', true, 4) on conflict (name) do nothing;
insert into categories (name, tier, type, counts_toward_runrate, sort_order) values ('Health Care', 1, 'variable', true, 5) on conflict (name) do nothing;
insert into categories (name, tier, type, counts_toward_runrate, sort_order) values ('Therapy', 1, 'fixed', true, 6) on conflict (name) do nothing;
insert into categories (name, tier, type, counts_toward_runrate, sort_order) values ('Transportation', 1, 'variable', true, 7) on conflict (name) do nothing;
insert into categories (name, tier, type, counts_toward_runrate, sort_order) values ('Tithe', 2, 'fixed', true, 8) on conflict (name) do nothing;
insert into categories (name, tier, type, counts_toward_runrate, sort_order) values ('Donations', 2, 'variable', true, 9) on conflict (name) do nothing;
insert into categories (name, tier, type, counts_toward_runrate, sort_order) values ('Family Support', 2, 'variable', true, 10) on conflict (name) do nothing;
insert into categories (name, tier, type, counts_toward_runrate, sort_order) values ('Fitness', 2, 'fixed', true, 11) on conflict (name) do nothing;
insert into categories (name, tier, type, counts_toward_runrate, sort_order) values ('Subscriptions', 2, 'fixed', true, 12) on conflict (name) do nothing;
insert into categories (name, tier, type, counts_toward_runrate, sort_order) values ('Advisor Fee', 2, 'fixed', true, 13) on conflict (name) do nothing;
insert into categories (name, tier, type, counts_toward_runrate, sort_order) values ('Shopping', 3, 'variable', true, 14) on conflict (name) do nothing;
insert into categories (name, tier, type, counts_toward_runrate, sort_order) values ('Eating Out', 3, 'variable', true, 15) on conflict (name) do nothing;
insert into categories (name, tier, type, counts_toward_runrate, sort_order) values ('Food Delivery', 3, 'variable', true, 16) on conflict (name) do nothing;
insert into categories (name, tier, type, counts_toward_runrate, sort_order) values ('Self Care', 3, 'variable', true, 17) on conflict (name) do nothing;
insert into categories (name, tier, type, counts_toward_runrate, sort_order) values ('Ride Share', 3, 'variable', true, 18) on conflict (name) do nothing;
insert into categories (name, tier, type, counts_toward_runrate, sort_order) values ('Experiences', 3, 'variable', true, 19) on conflict (name) do nothing;
insert into categories (name, tier, type, counts_toward_runrate, sort_order) values ('Gifts & People', 3, 'variable', true, 20) on conflict (name) do nothing;
insert into categories (name, tier, type, counts_toward_runrate, sort_order) values ('Flex', 3, 'variable', true, 21) on conflict (name) do nothing;
insert into categories (name, tier, type, counts_toward_runrate, sort_order) values ('Travel', 4, 'sinking_fund', true, 22) on conflict (name) do nothing;
insert into categories (name, tier, type, counts_toward_runrate, sort_order) values ('Investing', 4, 'fixed', false, 23) on conflict (name) do nothing;
insert into categories (name, tier, type, counts_toward_runrate, sort_order) values ('Savings', 4, 'fixed', false, 24) on conflict (name) do nothing;
insert into categories (name, tier, type, counts_toward_runrate, sort_order) values ('Income', 0, 'excluded', false, 25) on conflict (name) do nothing;
insert into categories (name, tier, type, counts_toward_runrate, sort_order) values ('Transfers', 0, 'excluded', false, 26) on conflict (name) do nothing;
insert into categories (name, tier, type, counts_toward_runrate, sort_order) values ('Fees', 0, 'excluded', false, 27) on conflict (name) do nothing;
insert into categories (name, tier, type, counts_toward_runrate, sort_order) values ('One-offs', 0, 'excluded', false, 28) on conflict (name) do nothing;

-- ---- Category rules (first match wins, lowest priority number first) ----
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('YSI ALLAN DOMB', 'contains', (select id from categories where name='Rent'), 1, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('INTEGRATED FINANCIAL', 'contains', (select id from categories where name='Advisor Fee'), 2, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('FID BKG', 'contains', (select id from categories where name='Investing'), 3, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('BARCLAYS', 'contains', (select id from categories where name='Savings'), 4, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('PENN MEDICINE', 'contains', (select id from categories where name='Health Care'), 5, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('SHADYGROVE', 'contains', (select id from categories where name='Health Care'), 6, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('IREDEEM HEALTH', 'contains', (select id from categories where name='Health Care'), 7, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('VISION CENTER', 'contains', (select id from categories where name='Health Care'), 8, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('CVS', 'contains', (select id from categories where name='Health Care'), 9, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('WALGREENS', 'contains', (select id from categories where name='Health Care'), 10, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('PHARMACY', 'contains', (select id from categories where name='Health Care'), 11, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('CPJ COUNSELING', 'contains', (select id from categories where name='Therapy'), 12, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('SPORTING CLUB', 'contains', (select id from categories where name='Fitness'), 13, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('CAPTYN', 'contains', (select id from categories where name='Fitness'), 14, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('CLASSPASS', 'contains', (select id from categories where name='Fitness'), 15, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('SOLIDCORE', 'contains', (select id from categories where name='Fitness'), 16, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('FREEDOM CHURCH', 'contains', (select id from categories where name='Tithe'), 17, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('PRACTICING THE WAY', 'contains', (select id from categories where name='Tithe'), 18, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('INTERVARSITY', 'contains', (select id from categories where name='Donations'), 19, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('GOFUNDME', 'contains', (select id from categories where name='Donations'), 20, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('FLEISHER', 'contains', (select id from categories where name='Donations'), 21, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('AFRO-AMERICAN CULTURAL', 'contains', (select id from categories where name='Donations'), 22, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('TMOBILE', 'contains', (select id from categories where name='Phone'), 23, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('T-MOBILE', 'contains', (select id from categories where name='Phone'), 24, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('COMCAST-XFINITY', 'contains', (select id from categories where name='Internet'), 25, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('XFINITY', 'contains', (select id from categories where name='Internet'), 26, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('UBER ONE', 'contains', (select id from categories where name='Subscriptions'), 27, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('UBER   *ONE', 'contains', (select id from categories where name='Subscriptions'), 28, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('WSJ', 'contains', (select id from categories where name='Subscriptions'), 29, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('AMAZON PRIME', 'contains', (select id from categories where name='Subscriptions'), 30, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('CLAUDE.AI', 'contains', (select id from categories where name='Subscriptions'), 31, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('GOOGLE ONE', 'contains', (select id from categories where name='Subscriptions'), 32, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('YOUVERSION', 'contains', (select id from categories where name='Subscriptions'), 33, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('DREXEL ONLINE', 'contains', (select id from categories where name='Subscriptions'), 34, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('COT*', 'contains', (select id from categories where name='Travel'), 35, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('EMIRATES', 'contains', (select id from categories where name='Travel'), 36, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('DELTA', 'contains', (select id from categories where name='Travel'), 37, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('AIRBNB', 'contains', (select id from categories where name='Travel'), 38, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('GRAB.COM', 'contains', (select id from categories where name='Travel'), 39, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('ATHENEE HOTEL', 'contains', (select id from categories where name='Travel'), 40, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('SIXT', 'contains', (select id from categories where name='Travel'), 41, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('AIRPORT RAILROAD', 'contains', (select id from categories where name='Travel'), 42, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('AMTRAK', 'contains', (select id from categories where name='Transportation'), 43, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('SEPTA', 'contains', (select id from categories where name='Transportation'), 44, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('NJ TRANSIT', 'contains', (select id from categories where name='Transportation'), 45, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('MTA*', 'contains', (select id from categories where name='Transportation'), 46, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('PARKING', 'contains', (select id from categories where name='Transportation'), 47, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('JRC SMART', 'contains', (select id from categories where name='Transportation'), 48, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('UBER EATS', 'contains', (select id from categories where name='Food Delivery'), 49, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('DOORDASH', 'contains', (select id from categories where name='Food Delivery'), 50, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('DD *', 'contains', (select id from categories where name='Food Delivery'), 51, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('GRUBHUB', 'contains', (select id from categories where name='Food Delivery'), 52, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('UBER', 'contains', (select id from categories where name='Ride Share'), 53, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('LYFT', 'contains', (select id from categories where name='Ride Share'), 54, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('WHOLEFDS', 'contains', (select id from categories where name='Groceries'), 55, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('TRADER JOE', 'contains', (select id from categories where name='Groceries'), 56, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('GIANT', 'contains', (select id from categories where name='Groceries'), 57, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('EDIBLE', 'contains', (select id from categories where name='Groceries'), 58, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('WINE AND SPIR', 'contains', (select id from categories where name='Groceries'), 59, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('STYLESEAT', 'contains', (select id from categories where name='Self Care'), 60, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('HAIRSTORY', 'contains', (select id from categories where name='Self Care'), 61, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('WWW.STYLES', 'contains', (select id from categories where name='Self Care'), 62, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('PERIWINKLE', 'contains', (select id from categories where name='Self Care'), 63, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('SEPHORA', 'contains', (select id from categories where name='Self Care'), 64, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('SATORI LASER', 'contains', (select id from categories where name='Self Care'), 65, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('BYUTIBLR', 'contains', (select id from categories where name='Self Care'), 66, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('TARGET', 'contains', (select id from categories where name='Shopping'), 67, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('WAL-MART', 'contains', (select id from categories where name='Shopping'), 68, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('WALMART', 'contains', (select id from categories where name='Shopping'), 69, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('T.J. MAXX', 'contains', (select id from categories where name='Shopping'), 70, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('TJ MAXX', 'contains', (select id from categories where name='Shopping'), 71, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('OLD NAVY', 'contains', (select id from categories where name='Shopping'), 72, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('H&M', 'contains', (select id from categories where name='Shopping'), 73, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('HM.COM', 'contains', (select id from categories where name='Shopping'), 74, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('NORDSTROM', 'contains', (select id from categories where name='Shopping'), 75, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('REI', 'contains', (select id from categories where name='Shopping'), 76, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('AMAZON MARK', 'contains', (select id from categories where name='Shopping'), 77, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('AMAZON.COM', 'contains', (select id from categories where name='Shopping'), 78, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('GROUPON', 'contains', (select id from categories where name='Shopping'), 79, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('HELLO MOLLY', 'contains', (select id from categories where name='Shopping'), 80, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('ASOS', 'contains', (select id from categories where name='Shopping'), 81, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('PAYPAL TO CHISOM', 'contains', (select id from categories where name='Shopping'), 82, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('IAT PAYPAL', 'contains', (select id from categories where name='Shopping'), 83, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('TICKETMASTER', 'contains', (select id from categories where name='Experiences'), 84, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('AXS.COM', 'contains', (select id from categories where name='Experiences'), 85, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('GAMETIME', 'contains', (select id from categories where name='Experiences'), 86, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('SOFAR', 'contains', (select id from categories where name='Experiences'), 87, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('GETYOURGU', 'contains', (select id from categories where name='Experiences'), 88, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('ROOTS PICNIC', 'contains', (select id from categories where name='Experiences'), 89, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('FILM PHILADELPHIA', 'contains', (select id from categories where name='Experiences'), 90, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('TST*', 'contains', (select id from categories where name='Eating Out'), 91, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('SQ *', 'contains', (select id from categories where name='Eating Out'), 92, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('KISMET', 'contains', (select id from categories where name='Eating Out'), 93, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('HANGAWI', 'contains', (select id from categories where name='Eating Out'), 94, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('STARR', 'contains', (select id from categories where name='Eating Out'), 95, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('CAFE', 'contains', (select id from categories where name='Eating Out'), 96, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('COFFEE', 'contains', (select id from categories where name='Eating Out'), 97, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('RESTAURANT', 'contains', (select id from categories where name='Eating Out'), 98, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('VENMO PAYMENT', 'contains', (select id from categories where name='Flex'), 99, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('ATM WITHDRAWAL', 'contains', (select id from categories where name='Flex'), 100, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('MEMBER FEE', 'contains', (select id from categories where name='Fees'), 101, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('ANNUAL FEE', 'contains', (select id from categories where name='Fees'), 102, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('FOREIGN TRANSACTION', 'contains', (select id from categories where name='Fees'), 103, 'seed') on conflict (pattern, category_id) do nothing;
insert into category_rules (pattern, match_type, category_id, priority, origin) values ('INTEREST CHARGE', 'contains', (select id from categories where name='Fees'), 104, 'seed') on conflict (pattern, category_id) do nothing;

-- ---- Budget targets (Month 1 and Stretch) ----
insert into budget_targets (category_id, scenario, amount) values ((select id from categories where name='Rent'), 'month1', 2600) on conflict do nothing;
insert into budget_targets (category_id, scenario, amount) values ((select id from categories where name='Rent'), 'stretch', 2600) on conflict do nothing;
insert into budget_targets (category_id, scenario, amount) values ((select id from categories where name='Phone'), 'month1', 60) on conflict do nothing;
insert into budget_targets (category_id, scenario, amount) values ((select id from categories where name='Phone'), 'stretch', 60) on conflict do nothing;
insert into budget_targets (category_id, scenario, amount) values ((select id from categories where name='Internet'), 'month1', 0) on conflict do nothing;
insert into budget_targets (category_id, scenario, amount) values ((select id from categories where name='Internet'), 'stretch', 0) on conflict do nothing;
insert into budget_targets (category_id, scenario, amount) values ((select id from categories where name='Groceries'), 'month1', 325) on conflict do nothing;
insert into budget_targets (category_id, scenario, amount) values ((select id from categories where name='Groceries'), 'stretch', 325) on conflict do nothing;
insert into budget_targets (category_id, scenario, amount) values ((select id from categories where name='Health Care'), 'month1', 175) on conflict do nothing;
insert into budget_targets (category_id, scenario, amount) values ((select id from categories where name='Health Care'), 'stretch', 175) on conflict do nothing;
insert into budget_targets (category_id, scenario, amount) values ((select id from categories where name='Therapy'), 'month1', 100) on conflict do nothing;
insert into budget_targets (category_id, scenario, amount) values ((select id from categories where name='Therapy'), 'stretch', 100) on conflict do nothing;
insert into budget_targets (category_id, scenario, amount) values ((select id from categories where name='Transportation'), 'month1', 175) on conflict do nothing;
insert into budget_targets (category_id, scenario, amount) values ((select id from categories where name='Transportation'), 'stretch', 175) on conflict do nothing;
insert into budget_targets (category_id, scenario, amount) values ((select id from categories where name='Tithe'), 'month1', 308) on conflict do nothing;
insert into budget_targets (category_id, scenario, amount) values ((select id from categories where name='Tithe'), 'stretch', 308) on conflict do nothing;
insert into budget_targets (category_id, scenario, amount) values ((select id from categories where name='Donations'), 'month1', 100) on conflict do nothing;
insert into budget_targets (category_id, scenario, amount) values ((select id from categories where name='Donations'), 'stretch', 100) on conflict do nothing;
insert into budget_targets (category_id, scenario, amount) values ((select id from categories where name='Family Support'), 'month1', 250) on conflict do nothing;
insert into budget_targets (category_id, scenario, amount) values ((select id from categories where name='Family Support'), 'stretch', 250) on conflict do nothing;
insert into budget_targets (category_id, scenario, amount) values ((select id from categories where name='Fitness'), 'month1', 190) on conflict do nothing;
insert into budget_targets (category_id, scenario, amount) values ((select id from categories where name='Fitness'), 'stretch', 190) on conflict do nothing;
insert into budget_targets (category_id, scenario, amount) values ((select id from categories where name='Subscriptions'), 'month1', 90) on conflict do nothing;
insert into budget_targets (category_id, scenario, amount) values ((select id from categories where name='Subscriptions'), 'stretch', 90) on conflict do nothing;
insert into budget_targets (category_id, scenario, amount) values ((select id from categories where name='Advisor Fee'), 'month1', 625) on conflict do nothing;
insert into budget_targets (category_id, scenario, amount) values ((select id from categories where name='Advisor Fee'), 'stretch', 625) on conflict do nothing;
insert into budget_targets (category_id, scenario, amount) values ((select id from categories where name='Shopping'), 'month1', 900) on conflict do nothing;
insert into budget_targets (category_id, scenario, amount) values ((select id from categories where name='Shopping'), 'stretch', 650) on conflict do nothing;
insert into budget_targets (category_id, scenario, amount) values ((select id from categories where name='Eating Out'), 'month1', 600) on conflict do nothing;
insert into budget_targets (category_id, scenario, amount) values ((select id from categories where name='Eating Out'), 'stretch', 525) on conflict do nothing;
insert into budget_targets (category_id, scenario, amount) values ((select id from categories where name='Food Delivery'), 'month1', 150) on conflict do nothing;
insert into budget_targets (category_id, scenario, amount) values ((select id from categories where name='Food Delivery'), 'stretch', 125) on conflict do nothing;
insert into budget_targets (category_id, scenario, amount) values ((select id from categories where name='Self Care'), 'month1', 325) on conflict do nothing;
insert into budget_targets (category_id, scenario, amount) values ((select id from categories where name='Self Care'), 'stretch', 300) on conflict do nothing;
insert into budget_targets (category_id, scenario, amount) values ((select id from categories where name='Ride Share'), 'month1', 150) on conflict do nothing;
insert into budget_targets (category_id, scenario, amount) values ((select id from categories where name='Ride Share'), 'stretch', 130) on conflict do nothing;
insert into budget_targets (category_id, scenario, amount) values ((select id from categories where name='Experiences'), 'month1', 150) on conflict do nothing;
insert into budget_targets (category_id, scenario, amount) values ((select id from categories where name='Experiences'), 'stretch', 150) on conflict do nothing;
insert into budget_targets (category_id, scenario, amount) values ((select id from categories where name='Gifts & People'), 'month1', 50) on conflict do nothing;
insert into budget_targets (category_id, scenario, amount) values ((select id from categories where name='Gifts & People'), 'stretch', 50) on conflict do nothing;
insert into budget_targets (category_id, scenario, amount) values ((select id from categories where name='Flex'), 'month1', 200) on conflict do nothing;
insert into budget_targets (category_id, scenario, amount) values ((select id from categories where name='Flex'), 'stretch', 150) on conflict do nothing;
insert into budget_targets (category_id, scenario, amount) values ((select id from categories where name='Travel'), 'month1', 927) on conflict do nothing;
insert into budget_targets (category_id, scenario, amount) values ((select id from categories where name='Travel'), 'stretch', 927) on conflict do nothing;
insert into budget_targets (category_id, scenario, amount) values ((select id from categories where name='Investing'), 'month1', 1250) on conflict do nothing;
insert into budget_targets (category_id, scenario, amount) values ((select id from categories where name='Investing'), 'stretch', 1250) on conflict do nothing;

-- ---- Your four accounts ----
insert into accounts (name, type, institution, last4) values ('AmEx', 'credit_card', 'American Express', null) on conflict (name) do nothing;
insert into accounts (name, type, institution, last4) values ('Venture X', 'credit_card', 'Capital One', '2044') on conflict (name) do nothing;
insert into accounts (name, type, institution, last4) values ('Quicksilver', 'credit_card', 'Capital One', '5916') on conflict (name) do nothing;
insert into accounts (name, type, institution, last4) values ('Checking', 'checking', 'Capital One', '6002') on conflict (name) do nothing;
